# Server Configuration

server.port=6040

# Engineering Knowledge Compiler

compiler.workspace.root=${user.home}/.ekc/workspace
compiler.workspace.repositories=repositories
compiler.workspace.temporary=temporary

# Logging

logging.level.ekc=INFO
logging.level.org.eclipse.jgit=WARN